# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Learn
    url: docs/
    weight: 20
  - name: About
    url: about/
    weight: 30


# sidebar:
#   - identifier: more
#     name: Need help?
#     params:
#       type: separator
#     weight: 1
#   - identifier: community
#     name: "Community"
#     pageRef: "/community"
#     weight: 2
#   - identifier: hugoDocs
#     name: "Hugo Docs ↗"
#     url: "https://docs.hugoblox.com"
#     weight: 3
